#!/bin/bash
#
#PBS -W group_list=yetiphyso
#PBS -N python_processing_new
#PBS -l nodes=1:ppn=16,walltime=4:00:00,mem=64000mb
#PBS -m abe
#PBS -M juliusbusecke@gmail.com

if [ "$1" == "dev" ]
then
  echo "DEV MODE ACTIVE"
  RUNDIR="/Users/juliusbusecke/Desktop/TimeMachineExcluded/run_debug_checkGradPosition"
  # PYTHONDIR="/Users/juliusbusecke/Work/PROJECTS/COLL_RYAN/ROUTINES/SETUP"
  # PBSDIR=$PYTHONDIR
  VALIDPATH="/Users/juliusbusecke/Work/PROJECTS/COLL_RYAN/OUTPUT/AVISO_validmask/validmask_combined.bin"
else
  RUNDIR=$PBS_O_WORKDIR
  # PYTHONDIR=/vega/physo/users/jb3210/tracer_model_scripts
  # PBSDIR=$RUNDIR
  VALIDPATH="/swot/SUM05/julius/offline_velocities/interpolatedvalidmask_combined.bin"
  module add anaconda/4.1.1-python-2.7.12
  source activate standard
fi

ODIR="$RUNDIR/output"

cd $RUNDIR
echo 'REMOVING OLD DIRECTORIES'

if [ "$1" == "dev" ]
then
  echo 'old directories not removed in dev mode'
else

  # current folder structure
  rm -r output
  rm -r plots
  rm -r movie*
  rm -r python*
fi

# remake the directory
mkdir $ODIR
echo 'START PYTHON READOUT'
python -c 'from mitgcm_surface_tracer.tracer_processing import main;\
main("'$RUNDIR/'","'$ODIR/'","'$VALIDPATH'",\
    koc_interval=10,\
    kappa=63,\
    spin_up_time = 2);\
exit();'
echo "PBS PROCESSING SCRIPT DONE"
