#!/bin/bash
#
#PBS -q infiniband
#PBS -l nodes=8,walltime=24:00:00
#PBS -W group_list=yetiphyso
#PBS -N HRSST_aviso_tracer
#PBS -m abe
#PBS -M juliusbusecke@gmail.com

RUNDIR=$PBS_O_WORKDIR

echo "Running MITgcm in $RUNDIR"
cd $RUNDIR
rm *.meta
rm *.data
rm STD*
rm finish_flag.txt
rm sss_aviso*
rm aviso_tracer_experiment*
rm HRSST_aviso_tracer*

# write the tracer source path into file
ls -l init_tracer.bin > tracersource.txt

module add intel-parallel-studio/2015

mpirun -n 128 ./mitgcmuv


# module add anaconda/4.1.1-python-2.7.12
# source activate standard
# echo "Rendering movie $RUNDIR"
# python -c 'from xarrayutils.visualization import mitgcm_Movie;\
#       mitgcm_Movie("$RUNDIR")'
