#!/bin/bash
#
#PBS -W group_list=yetiphyso
#PBS -N python_processing_new
#PBS -l nodes=4:ppn=16,walltime=4:00:00,mem=256000mb
#PBS -m abe
#PBS -M juliusbusecke@gmail.com

if [ "$1" == "dev" ]
then
  echo "DEV MODE ACTIVE"
  # RUNDIR="/Volumes/EXTERNAL_WORK/run_KOC_daily_PSI"
  RUNDIR="/Users/juliusbusecke/Desktop/TimeMachineExcluded/QC_setups/run_debug_checkGradPosition"
  VALIDPATH="/Users/juliusbusecke/Work/PROJECTS/COLL_RYAN/OUTPUT/AVISO_validmask/validmask_combined.bin"
else
  RUNDIR=$PBS_O_WORKDIR
  VALIDPATH="/vega/physo/users/jb3210/offline_velocities/aviso_DUACS2014_daily_msla/interpolated/validmask_combined.bin"
  # dont need this anymore since I have my own miniconda
  # module add anaconda/4.1.1-python-2.7.12
  source activate standard
fi

ODIR="$RUNDIR/output"
# reset months
RESET=3

cd $RUNDIR
echo 'REMOVING OLD DIRECTORIES'

if [ "$1" == "dev" ]
then
  echo 'old directories not removed in dev mode'
else

  # current folder structure
  rm -r output
  rm -r plots
  rm -r movie*
  rm -r python_*
fi

# remake the directory
mkdir $ODIR

echo 'START PYTHON READOUT'
python -c 'from mitgcm_surface_tracer.tracer_processing import main;\
main("'$RUNDIR/'","'$ODIR/'","'$VALIDPATH'",\
    koc_interval=10,\
    kappa=63,\
    spin_up_time = float("'$RESET'"));\
exit()' > pyout.txt


echo "PBS PROCESSING SCRIPT DONE"
qsub PBS_plot
