name: test_env
dependencies:
  - python=3.5
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - scipy
  - pip:
    - codecov
    - pytest-cov
    - xmitgcm
    - "--editable=git+https://github.com/jbusecke/xarrayutils.git#egg=xarrayutils"
