name: test_env
dependencies:
  - python=2.7
  - xarray
  - dask
  - numpy
  - pytest
  - future
  - scipy
  - cloudpickle
  - pip:
    - codecov
    - pytest-cov
    - "--editable=git+https://github.com/jbusecke/xmitgcm.git@master#egg=xmitgcm"
    - "--editable=git+https://github.com/jbusecke/xarrayutils.git@master#egg=xarrayutils"
    - "--editable=git+https://github.com/jbusecke/mitgcm_surface_tracer.git@master#egg=mitgcm_surface_tracer"
